#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certificates.cert-manager.io
  annotations:
    #! https://carvel.dev/kapp/docs/v0.54.0/apply/#kappk14sioexists
    kapp.k14s.io/exists: ""
    #! Without this change-rule, kapp waits (indefinitely) for this CRD to exist in an earlier change-group.
    kapp.k14s.io/change-rule.0: "upsert after upserting tap"
spec:
  group: cert-manager.io
  names:
    kind: Certificate
  scope: Namespaced
  versions:
    - name: v1
