#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: tap-install
  annotations:
    tekton.dev/git-0: #@ data.values.tap.credentials.git.server
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.tap.credentials.git.username
  password: #@ data.values.tap.credentials.git.token
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: git-ssh
  namespace: tap-install
spec:
  toNamespace: "*"
---

